### ISSUE TITLE
Buttons in navigator

### ISSUE THREAD

**Issue by jackie-ou** [designthriving/designthriving#32]
![image](https://user-images.githubusercontent.com/89358998/222942357-2d277523-7116-4f5d-8280-6d4ee3045106.png)

**Comment by Kevin-D23** [comment]
<img width="1509" alt="Screenshot 2023-03-11 at 12 09 55 AM" src="https://user-images.githubusercontent.com/116064184/224473162-fcaeb637-f202-4c02-9c0e-fc5a98df0bbf.png">
